name: octopus

on:
  push

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NOW_TOKEN: ${{ secrets.NOW_TOKEN }}

jobs:
  lint-and-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: cd octopus && make lint
#      - run: make test

  publish:
    timeout-minutes: 30
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    needs:
      - lint-and-test

    steps:
      - uses: actions/checkout@v1
      - run: cd octopus && NPM_TOKEN=$NPM_TOKEN make publish

  deploy-static:
    timeout-minutes: 30
#    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    needs:
      - lint-and-test

    steps:
      - uses: actions/checkout@v1
      - run: cd static && NOW_TOKEN=$NOW_TOKEN make deploy-static

  deploy-docs:
    timeout-minutes: 30
#    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    needs:
      - lint-and-test

    steps:
      - uses: actions/checkout@v1
      - run: cd docs && NOW_TOKEN=$NOW_TOKEN make deploy-docs

