name: octopus

on:
  push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint-and-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: make lint
#      - run: make test


  publish:
    timeout-minutes: 30
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    needs:
      - lint-and-test

    steps:
      - uses: actions/checkout@v1
      - run: GITHUB_TOKEN=$GITHUB_TOKEN make publish

     